# Ridge Regression

## Assignment

We're going back to our other **New York City** real estate dataset. Instead of predicting apartment rents, you'll predict property sales prices.

But not just for condos in Tribeca...

Instead, predict property sales prices for **One Family Dwellings** (`BUILDING_CLASS_CATEGORY` == `'01 ONE FAMILY DWELLINGS'`). 

Use a subset of the data where the **sale price was more than \\$100 thousand and less than $2 million.** 

The [NYC Department of Finance](https://www1.nyc.gov/site/finance/taxes/property-rolling-sales-data.page) has a glossary of property sales terms and NYC Building Class Code Descriptions. The data comes from the [NYC OpenData](https://data.cityofnewyork.us/browse?q=NYC%20calendar%20sales) portal.

- [X] Do train/test split. Use data from January — March 2019 to train. Use data from April 2019 to test.
- [X] Do one-hot encoding of categorical features.
- [X] Do feature selection with `SelectKBest`.
- [ ] Do [feature scaling](https://scikit-learn.org/stable/modules/preprocessing.html).
- [X] Fit a ridge regression model with multiple features.
- [X] Get mean absolute error for the test set.
- [X] As always, commit your notebook to your fork of the GitHub repo.

In [ ]:
%%capture
import sys

# If you're on Colab:
if 'google.colab' in sys.modules:
    DATA_PATH = 'https://raw.githubusercontent.com/LambdaSchool/DS-Unit-2-Applied-Modeling/master/data/'
    !pip install category_encoders==2.*

# If you're working locally:
else:
    DATA_PATH = '../data/'
    
# Ignore this Numpy warning when using Plotly Express:
# FutureWarning: Method .ptp is deprecated and will be removed in a future version. Use numpy.ptp instead.
import warnings
warnings.filterwarnings(action='ignore', category=FutureWarning, module='numpy')

## Load Data

In [ ]:
import pandas as pd
import pandas_profiling

# Read New York City property sales data
df = pd.read_csv(DATA_PATH+'condos/NYC_Citywide_Rolling_Calendar_Sales.csv')

# Change column names: replace spaces with underscores
df.columns = [col.replace(' ', '_') for col in df]

# SALE_PRICE was read as strings.
# Remove symbols, convert to integer
df['SALE_PRICE'] = (
    df['SALE_PRICE']
    .str.replace('$','')
    .str.replace('-','')
    .str.replace(',','')
    .astype(int)
)

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:14: FutureWarning: The default value of regex will change from True to False in a future version. In addition, single character regular expressions will *not* be treated as literal strings when regex=True.

In [ ]:
# BOROUGH is a numeric column, but arguably should be a categorical feature,
# so convert it from a number to a string
df['BOROUGH'] = df['BOROUGH'].astype(str)

In [ ]:
# Reduce cardinality for NEIGHBORHOOD feature

# Get a list of the top 10 neighborhoods
top10 = df['NEIGHBORHOOD'].value_counts()[:10].index

# At locations where the neighborhood is NOT in the top 10, 
# replace the neighborhood with 'OTHER'
df.loc[~df['NEIGHBORHOOD'].isin(top10), 'NEIGHBORHOOD'] = 'OTHER'

In [ ]:
df.head()

,BOROUGH,NEIGHBORHOOD,BUILDING_CLASS_CATEGORY,TAX_CLASS_AT_PRESENT,BLOCK,LOT,EASE-MENT,BUILDING_CLASS_AT_PRESENT,ADDRESS,APARTMENT_NUMBER,...,RESIDENTIAL_UNITS,COMMERCIAL_UNITS,TOTAL_UNITS,LAND_SQUARE_FEET,GROSS_SQUARE_FEET,YEAR_BUILT,TAX_CLASS_AT_TIME_OF_SALE,BUILDING_CLASS_AT_TIME_OF_SALE,SALE_PRICE,SALE_DATE
0,1,OTHER,13 CONDOS - ELEVATOR APARTMENTS,2,716,1246,NaN,R4,"447 WEST 18TH STREET, PH12A",PH12A,...,1.0,0.0,1.0,"10,733",1979.0,2007.0,2,R4,0,01/01/2019
1,1,OTHER,21 OFFICE BUILDINGS,4,812,68,NaN,O5,144 WEST 37TH STREET,NaN,...,0.0,6.0,6.0,"2,962",15435.0,1920.0,4,O5,0,01/01/2019
2,1,OTHER,21 OFFICE BUILDINGS,4,839,69,NaN,O5,40 WEST 38TH STREET,NaN,...,0.0,7.0,7.0,"2,074",11332.0,1930.0,4,O5,0,01/01/2019
3,1,OTHER,13 CONDOS - ELEVATOR APARTMENTS,2,592,1041,NaN,R4,"1 SHERIDAN SQUARE, 8C",8C,...,1.0,0.0,1.0,0,500.0,0.0,2,R4,0,01/01/2019
4,1,UPPER EAST SIDE (59-79),15 CONDOS - 2-10 UNIT RESIDENTIAL,2C,1379,1402,NaN,R1,"20 EAST 65TH STREET, B",B,...,1.0,0.0,1.0,0,6406.0,0.0,2,R1,0,01/01/2019

In [ ]:
# ('BUILDING_CLASS_CATEGORY' == '01 ONE FAMILY DWELLINGS')

df = df[df['BUILDING_CLASS_CATEGORY'] == '01 ONE FAMILY DWELLINGS']
df = df.drop('EASE-MENT', axis = 1)
df = df.drop('APARTMENT_NUMBER', axis = 1)

## Split Training and Test Data

In [ ]:
# - [X] Do train/test split. Use data from January — March 2019 to train. Use data from April 2019 to test.
# 01 - 03 2019 train, 04 2019 test
# property sales prices

train     = df[df['SALE_DATE'].str.contains('0[1-3]/[0-3][0-9]/2019')]
test      = df[df['SALE_DATE'].str.contains('04/[0-3][0-9]/2019')]

target    = 'SALE_PRICE'
high_card = ['BLOCK', 'LOT', 'ADDRESS', 'ZIP_CODE', 'LAND_SQUARE_FEET', 'GROSS_SQUARE_FEET', 'YEAR_BUILT', 'SALE_DATE']
features  = train.columns.drop([target] + high_card)

X_train   = train[features]
y_train   = train[target]
X_test    = test[features]
y_test    = test[target]

In [ ]:
train.head()

,BOROUGH,NEIGHBORHOOD,BUILDING_CLASS_CATEGORY,TAX_CLASS_AT_PRESENT,BLOCK,LOT,BUILDING_CLASS_AT_PRESENT,ADDRESS,ZIP_CODE,RESIDENTIAL_UNITS,COMMERCIAL_UNITS,TOTAL_UNITS,LAND_SQUARE_FEET,GROSS_SQUARE_FEET,YEAR_BUILT,TAX_CLASS_AT_TIME_OF_SALE,BUILDING_CLASS_AT_TIME_OF_SALE,SALE_PRICE,SALE_DATE
7,2,OTHER,01 ONE FAMILY DWELLINGS,1,4090,37,A1,1193 SACKET AVENUE,10461.0,1.0,0.0,1.0,"3,404",1328.0,1925.0,1,A1,0,01/01/2019
8,2,OTHER,01 ONE FAMILY DWELLINGS,1,4120,18,A5,1215 VAN NEST AVENUE,10461.0,1.0,0.0,1.0,"2,042",1728.0,1935.0,1,A5,0,01/01/2019
9,2,OTHER,01 ONE FAMILY DWELLINGS,1,4120,20,A5,1211 VAN NEST AVENUE,10461.0,1.0,0.0,1.0,"2,042",1728.0,1935.0,1,A5,0,01/01/2019
42,3,OTHER,01 ONE FAMILY DWELLINGS,1,6809,54,A1,2601 AVENUE R,11229.0,1.0,0.0,1.0,"3,333",1262.0,1925.0,1,A1,0,01/01/2019
44,3,OTHER,01 ONE FAMILY DWELLINGS,1,5495,801,A9,4832 BAY PARKWAY,11230.0,1.0,0.0,1.0,"6,800",1325.0,1930.0,1,A9,550000,01/01/2019

## Check NA Values

In [ ]:
train.isnull().sum()

BOROUGH                           0
NEIGHBORHOOD                      0
BUILDING_CLASS_CATEGORY           0
TAX_CLASS_AT_PRESENT              0
BLOCK                             0
LOT                               0
BUILDING_CLASS_AT_PRESENT         0
ADDRESS                           0
ZIP_CODE                          0
RESIDENTIAL_UNITS                 0
COMMERCIAL_UNITS                  0
TOTAL_UNITS                       0
LAND_SQUARE_FEET                  0
GROSS_SQUARE_FEET                 0
YEAR_BUILT                        0
TAX_CLASS_AT_TIME_OF_SALE         0
BUILDING_CLASS_AT_TIME_OF_SALE    0
SALE_PRICE                        0
SALE_DATE                         0
dtype: int64

In [ ]:
# - [X] Do one-hot encoding of categorical features.
import category_encoders as ce
encoder = ce.OneHotEncoder(use_cat_names = True)
X_train = encoder.fit_transform(X_train)
X_test  = encoder.transform(X_test)

/usr/local/lib/python3.7/dist-packages/statsmodels/tools/_testing.py:19: FutureWarning: pandas.util.testing is deprecated. Use the functions in the public API at pandas.testing instead.
  import pandas.util.testing as tm

In [ ]:
X_train.head()

,BOROUGH_2,BOROUGH_3,BOROUGH_4,BOROUGH_5,BOROUGH_1,NEIGHBORHOOD_OTHER,NEIGHBORHOOD_FLUSHING-NORTH,NEIGHBORHOOD_BOROUGH PARK,NEIGHBORHOOD_UPPER EAST SIDE (59-79),NEIGHBORHOOD_BEDFORD STUYVESANT,...,BUILDING_CLASS_AT_TIME_OF_SALE_A9,BUILDING_CLASS_AT_TIME_OF_SALE_A3,BUILDING_CLASS_AT_TIME_OF_SALE_A2,BUILDING_CLASS_AT_TIME_OF_SALE_A0,BUILDING_CLASS_AT_TIME_OF_SALE_S1,BUILDING_CLASS_AT_TIME_OF_SALE_A7,BUILDING_CLASS_AT_TIME_OF_SALE_A4,BUILDING_CLASS_AT_TIME_OF_SALE_A6,BUILDING_CLASS_AT_TIME_OF_SALE_A8,BUILDING_CLASS_AT_TIME_OF_SALE_S0
7,1,0,0,0,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
8,1,0,0,0,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
9,1,0,0,0,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
42,0,1,0,0,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
44,0,1,0,0,0,1,0,0,0,0,...,1,0,0,0,0,0,0,0,0,0

In [ ]:
X_train.describe().transpose()

,count,mean,std,min,25%,50%,75%,max
BOROUGH_2,4094.0,0.085247,0.279283,0.0,0.0,0.0,0.0,1.0
BOROUGH_3,4094.0,0.180020,0.384251,0.0,0.0,0.0,0.0,1.0
BOROUGH_4,4094.0,0.486810,0.499887,0.0,0.0,0.0,1.0,1.0
BOROUGH_5,4094.0,0.240107,0.427201,0.0,0.0,0.0,0.0,1.0
BOROUGH_1,4094.0,0.007816,0.088074,0.0,0.0,0.0,0.0,1.0
NEIGHBORHOOD_OTHER,4094.0,0.934538,0.247369,0.0,1.0,1.0,1.0,1.0
NEIGHBORHOOD_FLUSHING-NORTH,4094.0,0.035906,0.186079,0.0,0.0,0.0,0.0,1.0
NEIGHBORHOOD_BOROUGH PARK,4094.0,0.007328,0.085299,0.0,0.0,0.0,0.0,1.0
NEIGHBORHOOD_UPPER EAST SIDE (59-79),4094.0,0.001954,0.044167,0.0,0.0,0.0,0.0,1.0
NEIGHBORHOOD_BEDFORD STUYVESANT,4094.0,0.003908,0.062401,0.0,0.0,0.0,0.0,1.0
NEIGHBORHOOD_FOREST HILLS,4094.0,0.010259,0.100778,0.0,0.0,0.0,0.0,1.0
NEIGHBORHOOD_ASTORIA,4094.0,0.005129,0.071445,0.0,0.0,0.0,0.0,1.0
NEIGHBORHOOD_UPPER EAST SIDE (79-96),4094.0,0.000489,0.022100,0.0,0.0,0.0,0.0,1.0
NEIGHBORHOOD_UPPER WEST SIDE (79-96),4094.0,0.000489,0.022100,0.0,0.0,0.0,0.0,1.0
BUILDING_CLASS_CATEGORY_01 ONE FAMILY DWELLINGS,4094.0,1.000000,0.000000,1.0,1.0,1.0,1.0,1.0
TAX_CLASS_AT_PRESENT_1,4094.0,0.991207,0.093371,0.0,1.0,1.0,1.0,1.0
TAX_CLASS_AT_PRESENT_1D,4094.0,0.008305,0.090763,0.0,0.0,0.0,0.0,1.0
TAX_CLASS_AT_PRESENT_1B,4094.0,0.000489,0.022100,0.0,0.0,0.0,0.0,1.0
BUILDING_CLASS_AT_PRESENT_A1,4094.0,0.376649,0.484605,0.0,0.0,0.0,1.0,1.0
BUILDING_CLASS_AT_PRESENT_A5,4094.0,0.295554,0.456347,0.0,0.0,0.0,1.0,1.0
BUILDING_CLASS_AT_PRESENT_A9,4094.0,0.070835,0.256581,0.0,0.0,0.0,0.0,1.0
BUILDING_CLASS_AT_PRESENT_A3,4094.0,0.022228,0.147441,0.0,0.0,0.0,0.0,1.0
BUILDING_CLASS_AT_PRESENT_A2,4094.0,0.161212,0.367771,0.0,0.0,0.0,0.0,1.0
BUILDING_CLASS_AT_PRESENT_A0,4094.0,0.023205,0.150571,0.0,0.0,0.0,0.0,1.0
BUILDING_CLASS_AT_PRESENT_S1,4094.0,0.023205,0.150571,0.0,0.0,0.0,0.0,1.0
BUILDING_CLASS_AT_PRESENT_A7,4094.0,0.000489,0.022100,0.0,0.0,0.0,0.0,1.0
BUILDING_CLASS_AT_PRESENT_A4,4094.0,0.011969,0.108758,0.0,0.0,0.0,0.0,1.0
BUILDING_CLASS_AT_PRESENT_A6,4094.0,0.004641,0.067974,0.0,0.0,0.0,0.0,1.0
BUILDING_CLASS_AT_PRESENT_A8,4094.0,0.008305,0.090763,0.0,0.0,0.0,0.0,1.0
BUILDING_CLASS_AT_PRESENT_B2,4094.0,0.000244,0.015629,0.0,0.0,0.0,0.0,1.0
BUILDING_CLASS_AT_PRESENT_S0,4094.0,0.000733,0.027063,0.0,0.0,0.0,0.0,1.0
BUILDING_CLASS_AT_PRESENT_B3,4094.0,0.000244,0.015629,0.0,0.0,0.0,0.0,1.0
BUILDING_CLASS_AT_PRESENT_V0,4094.0,0.000489,0.022100,0.0,0.0,0.0,0.0,1.0
RESIDENTIAL_UNITS,4094.0,0.991451,0.092076,0.0,1.0,1.0,1.0,1.0
COMMERCIAL_UNITS,4094.0,0.024670,0.159792,0.0,0.0,0.0,0.0,2.0
TOTAL_UNITS,4094.0,1.016121,0.185562,0.0,1.0,1.0,1.0,3.0
TAX_CLASS_AT_TIME_OF_SALE,4094.0,1.000000,0.000000,1.0,1.0,1.0,1.0,1.0
BUILDING_CLASS_AT_TIME_OF_SALE_A1,4094.0,0.376893,0.484667,0.0,0.0,0.0,1.0,1.0
BUILDING_CLASS_AT_TIME_OF_SALE_A5,4094.0,0.295310,0.456238,0.0,0.0,0.0,1.0,1.0
BUILDING_CLASS_AT_TIME_OF_SALE_A9,4094.0,0.070835,0.256581,0.0,0.0,0.0,0.0,1.0
BUILDING_CLASS_AT_TIME_OF_SALE_A3,4094.0,0.022228,0.147441,0.0,0.0,0.0,0.0,1.0
BUILDING_CLASS_AT_TIME_OF_SALE_A2,4094.0,0.162189,0.368669,0.0,0.0,0.0,0.0,1.0
BUILDING_CLASS_AT_TIME_OF_SALE_A0,4094.0,0.023205,0.150571,0.0,0.0,0.0,0.0,1.0
BUILDING_CLASS_AT_TIME_OF_SALE_S1,4094.0,0.023205,0.150571,0.0,0.0,0.0,0.0,1.0
BUILDING_CLASS_AT_TIME_OF_SALE_A7,4094.0,0.000489,0.022100,0.0,0.0,0.0,0.0,1.0
BUILDING_CLASS_AT_TIME_OF_SALE_A4,4094.0,0.011969,0.108758,0.0,0.0,0.0,0.0,1.0
BUILDING_CLASS_AT_TIME_OF_SALE_A6,4094.0,0.004641,0.067974,0.0,0.0,0.0,0.0,1.0
BUILDING_CLASS_AT_TIME_OF_SALE_A8,4094.0,0.008305,0.090763,0.0,0.0,0.0,0.0,1.0
BUILDING_CLASS_AT_TIME_OF_SALE_S0,4094.0,0.000733,0.027063,0.0,0.0,0.0,0.0,1.0

In [ ]:
# - [X] Do feature selection with `SelectKBest`.
from sklearn.feature_selection import f_regression, SelectKBest
selector         = SelectKBest(score_func = f_regression, k = 15)
X_train_selected = selector.fit_transform(X_train, y_train)
X_test_selected  = selector.transform(X_test)

/usr/local/lib/python3.7/dist-packages/sklearn/feature_selection/_univariate_selection.py:289: RuntimeWarning: divide by zero encountered in true_divide
  correlation_coefficient /= X_norms
/usr/local/lib/python3.7/dist-packages/sklearn/feature_selection/_univariate_selection.py:358: RuntimeWarning: invalid value encountered in true_divide
  f_statistic = corr_coef_squared / (1 - corr_coef_squared) * deg_of_freedom

In [ ]:
# - [ ] Do [feature scaling](https://scikit-learn.org/stable/modules/preprocessing.html).
from sklearn import preprocessing

In [ ]:
# - [X] Fit a ridge regression model with multiple features.
from sklearn.linear_model import Ridge
model = Ridge(alpha = 15)
model.fit(X_train, y_train)
y_pred = model.predict(X_test)

In [25]:
pd.DataFrame([X_train.columns, model.coef_], index=['Feature', 'Coef']).transpose()

                                            Feature            Coef
0                                         BOROUGH_2  -564890.865531
1                                         BOROUGH_3  -498025.751715
2                                         BOROUGH_4  -585556.444772
3                                         BOROUGH_5  -596544.546845
4                                         BOROUGH_1  2245017.608863
5                                NEIGHBORHOOD_OTHER  -476478.491257
6                       NEIGHBORHOOD_FLUSHING-NORTH  -375910.679308
7                         NEIGHBORHOOD_BOROUGH PARK  -361438.369913
8              NEIGHBORHOOD_UPPER EAST SIDE (59-79)  1072301.157575
9                   NEIGHBORHOOD_BEDFORD STUYVESANT  -576027.899374
10                        NEIGHBORHOOD_FOREST HILLS  -176141.913921
11                             NEIGHBORHOOD_ASTORIA  -184856.238708
12             NEIGHBORHOOD_UPPER EAST SIDE (79-96)  1168375.040983
13             NEIGHBORHOOD_UPPER WEST SIDE (79-96)   -89822.606076
14  BUILDING_CLASS_CATEGORY_01 ONE FAMILY DWELLINGS             0.0
15                           TAX_CLASS_AT_PRESENT_1    73257.496334
16                          TAX_CLASS_AT_PRESENT_1D   -33358.051815
17                          TAX_CLASS_AT_PRESENT_1B   -39899.444519
18                     BUILDING_CLASS_AT_PRESENT_A1  -112706.537176
19                     BUILDING_CLASS_AT_PRESENT_A5  -157064.638001
20                     BUILDING_CLASS_AT_PRESENT_A9  -127217.184064
21                     BUILDING_CLASS_AT_PRESENT_A3    22609.732026
22                     BUILDING_CLASS_AT_PRESENT_A2  -145354.408968
23                     BUILDING_CLASS_AT_PRESENT_A0   -83060.658541
24                     BUILDING_CLASS_AT_PRESENT_S1  -128806.018495
25                     BUILDING_CLASS_AT_PRESENT_A7   262320.026985
26                     BUILDING_CLASS_AT_PRESENT_A4   591266.118228
27                     BUILDING_CLASS_AT_PRESENT_A6  -164215.558615
28                     BUILDING_CLASS_AT_PRESENT_A8   -33358.051815
29                     BUILDING_CLASS_AT_PRESENT_B2     19900.62668
30                     BUILDING_CLASS_AT_PRESENT_S0    69379.039671
31                     BUILDING_CLASS_AT_PRESENT_B3    26206.956605
32                     BUILDING_CLASS_AT_PRESENT_V0   -39899.444519
33                                RESIDENTIAL_UNITS    49376.314354
34                                 COMMERCIAL_UNITS     9952.060846
35                                      TOTAL_UNITS      59328.3752
36                        TAX_CLASS_AT_TIME_OF_SALE             0.0
37                BUILDING_CLASS_AT_TIME_OF_SALE_A1  -135715.792991
38                BUILDING_CLASS_AT_TIME_OF_SALE_A5  -137317.397172
39                BUILDING_CLASS_AT_TIME_OF_SALE_A9  -127217.184064
40                BUILDING_CLASS_AT_TIME_OF_SALE_A3    22609.732026
41                BUILDING_CLASS_AT_TIME_OF_SALE_A2  -135884.255217
42                BUILDING_CLASS_AT_TIME_OF_SALE_A0   -83060.658541
43                BUILDING_CLASS_AT_TIME_OF_SALE_S1  -128806.018495
44                BUILDING_CLASS_AT_TIME_OF_SALE_A7   262320.026985
45                BUILDING_CLASS_AT_TIME_OF_SALE_A4   591266.118228
46                BUILDING_CLASS_AT_TIME_OF_SALE_A6  -164215.558615
47                BUILDING_CLASS_AT_TIME_OF_SALE_A8   -33358.051815
48                BUILDING_CLASS_AT_TIME_OF_SALE_S0    69379.039671

In [ ]:
|# - [X] Get mean absolute error for the test set.
import numpy as np
from sklearn.metrics import mean_absolute_error
mean_absolute_error(y_test, y_pred)

387119.5244040678

## Stretch Goals
- [ ] Add your own stretch goal(s) !
- [ ] Instead of `Ridge`, try `LinearRegression`. Depending on how many features you select, your errors will probably blow up! 💥
- [ ] Instead of `Ridge`, try [`RidgeCV`](https://scikit-learn.org/stable/modules/generated/sklearn.linear_model.RidgeCV.html).
- [ ] Learn more about feature selection:
    - ["Permutation importance"](https://www.kaggle.com/dansbecker/permutation-importance)
    - [scikit-learn's User Guide for Feature Selection](https://scikit-learn.org/stable/modules/feature_selection.html)
    - [mlxtend](http://rasbt.github.io/mlxtend/) library
    - scikit-learn-contrib libraries: [boruta_py](https://github.com/scikit-learn-contrib/boruta_py) & [stability-selection](https://github.com/scikit-learn-contrib/stability-selection)
    - [_Feature Engineering and Selection_](http://www.feat.engineering/) by Kuhn & Johnson.
- [ ] Try [statsmodels](https://www.statsmodels.org/stable/index.html) if you’re interested in more inferential statistical approach to linear regression and feature selection, looking at p values and 95% confidence intervals for the coefficients.
- [ ] Read [_An Introduction to Statistical Learning_](http://faculty.marshall.usc.edu/gareth-james/ISL/ISLR%20Seventh%20Printing.pdf), Chapters 1-3, for more math & theory, but in an accessible, readable way.
- [ ] Try [scikit-learn pipelines](https://scikit-learn.org/stable/modules/compose.html).